version: "3.9"
services:
  rank-svc:
    container_name: rank-svc
    depends_on:
      - rank-db-cassandra
    image: rank-svc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  rank-db-cassandra:
    container_name: rank-db-cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    expose:
      - 9042