name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      rank-db-cassandra:
        image: cassandra:latest
        ports:
          - "9042:9042"
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        steps:
          - run: docker ps
          - run: docker exec ${{ job.services.rank-db-cassandra.id }} cqlsh --debug

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn install

    - name: SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.host.url="https://sonarcloud.io" -Dsonar.organization=chesstournamentmanager -Dsonar.projectKey=ChessTournamentManager_round-svc

    - name: Login to DockerHub
      if: success() && github.ref == 'refs/heads/main'
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      if: success() && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        push: true
        tags: judahlit/chess_tournament_manager:round-svc